import { StyleSheet, Dimensions } from 'react-native';

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');

// Color palette
export const Colors = {
  primary: '#3498db',
  secondary: '#2ecc71',
  accent: '#e74c3c',
  background: '#f8f9fa',
  surface: '#ffffff',
  textPrimary: '#2c3e50',
  textSecondary: '#7f8c8d',
  textOnPrimary: '#ffffff',
  border: '#dee2e6',
  gray: '#95a5a6',
  black: '#000000',
  white: '#ffffff',
  success: '#27ae60',
  warning: '#f39c12',
  error: '#e74c3c',
  info: '#3498db',
};

// Common styles used across components
export const CommonStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.background,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: Colors.textSecondary,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: Colors.background,
  },
  errorText: {
    fontSize: 16,
    color: Colors.error,
    textAlign: 'center',
    marginBottom: 20,
  },
  retryButton: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
  },
  retryButtonText: {
    color: Colors.textOnPrimary,
    fontSize: 16,
    fontWeight: 'bold',
  },
  input: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    backgroundColor: Colors.surface,
    color: '#2c3e50',
    marginBottom: 16,
  },
  button: {
    backgroundColor: Colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 12,
  },
  buttonText: {
    color: Colors.textOnPrimary,
    fontSize: 16,
    fontWeight: 'bold',
  },
  disabledButton: {
    backgroundColor: Colors.gray,
    opacity: 0.6,
  },
  discoveryField: {
    backgroundColor: Colors.surface,
    borderRadius: 12,
    padding: 20,
    marginVertical: 15,
    borderWidth: 2,
    borderColor: Colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 80,
  },
  discoveryContent: {
    alignItems: 'center',
  },
  discoveryButtonText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: Colors.primary,
  },
  pinyinText: {
    fontSize: 18,
    color: Colors.textPrimary,
    fontWeight: '600',
    marginBottom: 8,
  },
  translationText: {
    fontSize: 16,
    color: Colors.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
  },
  navigationContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
    paddingHorizontal: 20,
  },
  navButton: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    minWidth: 100,
    alignItems: 'center',
  },
  navButtonText: {
    color: Colors.textOnPrimary,
    fontSize: 16,
    fontWeight: 'bold',
  },
});

// Landing Page styles
export const LandingPageStyles = StyleSheet.create({
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 20,
  },
  topBarSpacer: {
    flex: 1,
  },
  topButtonContainer: {
    flexDirection: 'row',
    gap: 10,
  },
  topLoginButton: {
    backgroundColor: '#3498db',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
  },
  topLoginButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  topLogoutButton: {
    backgroundColor: '#e74c3c',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
  },
  topLogoutButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  topAdminButton: {
    backgroundColor: '#9b59b6',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
  },
  topAdminButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  loginContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  loginTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2c3e50',
    marginBottom: 30,
    textAlign: 'center',
  },
  loginButtons: {
    width: '100%',
    gap: 12,
  },
  loginButton: {
    backgroundColor: '#3498db',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  loginButtonText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  registerButton: {
    backgroundColor: '#27ae60',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  registerButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  cancelButton: {
    backgroundColor: 'transparent',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#bdc3c7',
  },
  cancelButtonText: {
    color: '#7f8c8d',
    fontSize: 16,
    fontWeight: '600',
  },
  header: {
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 40,
  },
  appTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#2c3e50',
    textAlign: 'center',
    marginBottom: 10,
  },
  appSubtitle: {
    fontSize: 16,
    color: '#7f8c8d',
    textAlign: 'center',
    lineHeight: 24,
  },
  usersListContainer: {
    flex: 1,
    padding: 20,
  },
  userCard: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  userName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2c3e50',
    marginBottom: 8,
  },
  userStats: {
    fontSize: 14,
    color: '#7f8c8d',
    marginBottom: 4,
  },
  userProgress: {
    fontSize: 14,
    color: '#3498db',
    fontWeight: '600',
    marginBottom: 4,
  },
  userDate: {
    fontSize: 12,
    color: '#95a5a6',
    marginBottom: 2,
  },
  noUsersText: {
    fontSize: 16,
    color: '#7f8c8d',
    textAlign: 'center',
    marginTop: 50,
  },
  adminButton: {
    backgroundColor: '#9b59b6',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 10,
  },
  adminButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  featuresContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
  },
  featuresTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2c3e50',
    marginBottom: 20,
    textAlign: 'center',
  },
  featureCard: {
    backgroundColor: '#e3f2fd',
    borderRadius: 20,
    padding: 35,
    margin: 20,
    marginBottom: 15,
    alignSelf: 'center',
    minWidth: 320,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
    borderWidth: 1,
    borderColor: '#bbdefb',
  },
  featureCardContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  featureLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 0,
  },
  featureContent: {
    alignItems: 'flex-start',
    marginLeft: 15,
    flexShrink: 0,
  },
  featureTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#3498db',
    marginBottom: 0,
  },
  featureDescription: {
    fontSize: 14,
    color: '#7f8c8d',
    textAlign: 'center',
    lineHeight: 20,
  },
  disabledFeature: {
    opacity: 0.6,
    backgroundColor: '#f8f9fa',
  },
  disabledText: {
    color: '#85c1e9',
  },
  authContainer: {
    marginTop: 20,
    paddingHorizontal: 20,
  },
  loginPromptButton: {
    backgroundColor: '#3498db',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 12,
  },
  loginPromptText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  guestButton: {
    backgroundColor: 'transparent',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#bdc3c7',
  },
  guestButtonText: {
    color: '#7f8c8d',
    fontSize: 16,
    fontWeight: '600',
  },
  pieChartContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 15,
  },
});


// Simple Character Card styles
export const SimpleCharacterCardStyles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: '#f8f9fa',
    borderBottomWidth: 1,
    borderBottomColor: '#dee2e6',
  },
  headerTitleContainer: {
    flex: 1,
    alignItems: 'center',
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2c3e50',
    textAlign: 'center',
  },
  userIndicator: {
    fontSize: 12,
    color: '#3498db',
    fontWeight: '600',
    marginTop: 2,
  },
  backButton: {
    backgroundColor: '#3498db',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 8,
  },
  backButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  characterCounter: {
    fontSize: 14,
    color: '#7f8c8d',
    fontWeight: '600',
  },
  characterContainer: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 20,
    margin: 15,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    minHeight: 200,
  },
  individualCharacter: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderRadius: 8,
    margin: 5,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  characterRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  characterGrid: {
    alignItems: 'center',
  },
  hanziWriterContainer: {
    backgroundColor: 'transparent',
  },
  navigationContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
    paddingHorizontal: 20,
  },
  navButton: {
    backgroundColor: '#3498db',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    minWidth: 100,
    alignItems: 'center',
  },
  navButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  disabledButton: {
    backgroundColor: '#bdc3c7',
    opacity: 0.6,
  },
  viewedStar: {
    position: 'absolute',
    top: 8,
    right: 8,
    zIndex: 10,
    backgroundColor: 'transparent',
    padding: 0,
  },
  starText: {
    fontSize: 24,
    color: '#3498db',
  },
  discoveryField: {
    backgroundColor: '#f8f9fa',
    borderRadius: 12,
    padding: 20,
    margin: 15,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    borderWidth: 2,
    borderColor: '#3498db',
    borderStyle: 'dashed',
    minHeight: 80,
    maxWidth: 400,
  },
  discoveryContent: {
    alignItems: 'center',
    alignSelf: 'center',
    width: '35%',
    minWidth: 250,
  },
  discoveryButtonText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#3498db',
  },
  pinyinText: {
    fontSize: 22,
    color: '#3498db',
    textAlign: 'center',
    marginBottom: 6,
    fontWeight: 'bold',
  },
  translationText: {
    fontSize: 18,
    color: '#2c3e50',
    textAlign: 'center',
    marginBottom: 8,
    lineHeight: 20,
    fontWeight: 'bold',
  },
  sentenceContainerCompact: {
    backgroundColor: '#3498db',
    borderRadius: 25,
    paddingHorizontal: 30,
    paddingVertical: 15,
    margin: 15,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: '#2980b9',
    minWidth: 120,
    height: 50,
  },
  sentenceDots: {
    fontSize: 24,
    color: '#ffffff',
    fontWeight: 'bold',
    textAlign: 'center',
    backgroundColor: 'transparent',
  },
  strokePracticeHint: {
    fontSize: 14,
    color: '#7f8c8d',
    textAlign: 'center',
    marginTop: 10,
    marginBottom: 10,
    fontStyle: 'italic',
  },
  soundButtonRound: {
    position: 'absolute',
    bottom: 15,
    right: 20,
    backgroundColor: '#3498db',
    borderRadius: 25,
    width: 50,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  soundButtonIconRound: {
    fontSize: 20,
    color: '#ffffff',
  },
});

// Character Navigation Ribbon styles
export const CharacterNavigationRibbonStyles = StyleSheet.create({
  container: {
    backgroundColor: Colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    paddingVertical: 10,
  },
  scrollView: {
    paddingHorizontal: 10,
  },
  characterButton: {
    marginHorizontal: 5,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#000000',
    minWidth: 50,
    alignItems: 'center',
  },
  selectedCharacterButton: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  characterButtonText: {
    fontSize: 16,
    color: '#000000',
    fontWeight: '500',
  },
  selectedCharacterButtonText: {
    color: Colors.textOnPrimary,
    fontWeight: 'bold',
  },
  viewedCharacterButton: {
    backgroundColor: Colors.background,
    borderColor: '#3498db',
    borderWidth: 2,
  },
  viewedCharacterButtonText: {
    color: '#3498db',
    fontWeight: 'bold',
  },
  characterItem: {
    marginHorizontal: 5,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#000000',
    minWidth: 50,
    alignItems: 'center',
  },
  currentCharacterItem: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  viewedCharacterItem: {
    backgroundColor: '#ffffff',
    borderColor: '#3498db',
    borderWidth: 2,
  },
  currentCharacterText: {
    color: Colors.textOnPrimary,
    fontWeight: 'bold',
  },
  viewedCharacterText: {
    color: '#3498db',
    fontWeight: 'bold',
  },
  characterText: {
    fontSize: 16,
    color: '#000000',
    fontWeight: '500',
  },
  positionText: {
    fontSize: 10,
    color: '#000000',
    fontWeight: '400',
    marginTop: 2,
  },
  currentPositionText: {
    color: Colors.textOnPrimary,
    fontWeight: 'bold',
  },
});

// Sentence Popup styles
export const SentencePopupStyles = StyleSheet.create({
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    maxWidth: '90%',
  },
  closeButtonTopRight: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: '#e74c3c',
    borderRadius: 15,
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  closeButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  sentenceText: {
    fontSize: 26,
    color: '#3498db',
    textAlign: 'center',
    marginBottom: 15,
    lineHeight: 36,
    fontWeight: 'bold',
  },
  pinyinText: {
    fontSize: 22,
    color: '#000000',
    textAlign: 'center',
    marginBottom: 15,
    fontWeight: 'bold',
  },
  translationText: {
    fontSize: 22,
    color: '#2c3e50',
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 30,
    fontWeight: 'bold',
  },
  playButton: {
    backgroundColor: '#3498db',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    marginTop: 10,
  },
  playButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  content: {
    width: '100%',
    paddingTop: 20,
    paddingBottom: 20,
  },
  sentenceSection: {
    marginBottom: 20,
    paddingHorizontal: 10,
  },
  sentencePinyin: {
    fontSize: 18,
    color: '#7f8c8d',
    textAlign: 'center',
    marginBottom: 5,
    fontStyle: 'italic',
    fontWeight: '500',
  },
  sentenceTranslation: {
    fontSize: 16,
    color: '#2c3e50',
    textAlign: 'center',
    marginBottom: 5,
    lineHeight: 22,
    fontWeight: '400',
  },
  soundButtonRound: {
    position: 'absolute',
    bottom: 15,
    right: 20,
    backgroundColor: '#3498db',
    borderRadius: 25,
    width: 50,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  soundButtonIconRound: {
    fontSize: 20,
    color: '#ffffff',
  },
});

// Interactive Stroke Practice Modal styles
export const InteractiveStrokePracticeModalStyles = StyleSheet.create({
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalView: {
    margin: 0,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 0,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: screenWidth * 0.95,
    height: screenHeight * 0.7,
  },
  header: {
    width: '100%',
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#dee2e6',
    marginBottom: 0,
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2c3e50',
    textAlign: 'center',
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#2c3e50',
    textAlign: 'center',
    marginBottom: 5,
  },
  closeButton: {
    position: 'absolute',
    top: 15,
    right: 15,
    backgroundColor: '#e74c3c',
    borderRadius: 15,
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  modeSelector: {
    flexDirection: 'row',
    marginBottom: 0,
    justifyContent: 'center',
  },
  modeButton: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    marginHorizontal: 5,
    backgroundColor: '#ecf0f1',
  },
  activeModeButton: {
    backgroundColor: '#3498db',
  },
  modeButtonText: {
    fontSize: 16,
    color: '#7f8c8d',
    fontWeight: '500',
  },
  activeModeButtonText: {
    color: '#ffffff',
    fontWeight: 'bold',
  },
  contentContainer: {
    flex: 1,
    width: '100%',
    padding: 20,
  },
});

// Simple Drawing Grid styles
export const SimpleDrawingGridStyles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 0,
    margin: 0,
    backgroundColor: '#ffffff',
  },
  header: {
    alignItems: 'center',
    marginBottom: 0,
    paddingHorizontal: 20,
    paddingTop: 0,
  },
  characterText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2c3e50',
    marginBottom: -5,
  },
  strokeInfo: {
    fontSize: 14,
    color: '#7f8c8d',
    textAlign: 'center',
    marginTop: 2,
  },
  drawingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 0,
    margin: 0,
  },
  webViewContainer: {
    width: 300,
    height: 300,
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#dee2e6',
  },
  fallbackContainer: {
    width: 300,
    height: 300,
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#dee2e6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fallbackText: {
    fontSize: 18,
    color: '#7f8c8d',
    textAlign: 'center',
  },
  controls: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    margin: 0,
  },
  controlButton: {
    backgroundColor: '#3498db',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    marginHorizontal: 10,
  },
  controlButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  disabledButton: {
    backgroundColor: '#bdc3c7',
    opacity: 0.6,
  },
});

// Login Page styles
export const LoginPageStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 30,
    width: '100%',
    maxWidth: 400,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#2c3e50',
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: '#7f8c8d',
    textAlign: 'center',
    marginBottom: 30,
  },
  input: {
    borderWidth: 2,
    borderColor: '#bdc3c7',
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    backgroundColor: '#ffffff',
    color: '#2c3e50',
    marginBottom: 16,
  },
  passwordContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#bdc3c7',
    borderRadius: 12,
    backgroundColor: '#ffffff',
    marginBottom: 16,
  },
  passwordInput: {
    flex: 1,
    padding: 16,
    fontSize: 16,
    color: '#2c3e50',
  },
  eyeIcon: {
    padding: 16,
  },
  loginButton: {
    backgroundColor: '#3498db',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 16,
  },
  loginButtonText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  registerButton: {
    backgroundColor: 'transparent',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#3498db',
  },
  registerButtonText: {
    color: '#3498db',
    fontSize: 16,
    fontWeight: '600',
  },
});

// Register Page styles
export const RegisterPageStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
    padding: 20,
  },
  header: {
    alignItems: 'center',
    marginTop: 60,
    marginBottom: 40,
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#2c3e50',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: '#7f8c8d',
    textAlign: 'center',
  },
  form: {
    flex: 1,
  },
  fieldContainer: {
    marginBottom: 20,
  },
  fieldLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2c3e50',
    marginBottom: 8,
  },
  input: {
    borderWidth: 2,
    borderColor: '#bdc3c7',
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    backgroundColor: '#ffffff',
    color: '#2c3e50',
  },
  passwordContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#bdc3c7',
    borderRadius: 12,
    backgroundColor: '#ffffff',
  },
  passwordInput: {
    flex: 1,
    padding: 16,
    fontSize: 16,
    color: '#2c3e50',
  },
  eyeIcon: {
    padding: 16,
  },
  registerButton: {
    backgroundColor: '#3498db',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 16,
  },
  registerButtonText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  backButton: {
    backgroundColor: 'transparent',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#3498db',
  },
  backButtonText: {
    color: '#3498db',
    fontSize: 16,
    fontWeight: '600',
  },
  disabledButton: {
    backgroundColor: '#bdc3c7',
    opacity: 0.6,
  },
});

// Free Drawing styles
export const FreeDrawingStyles = StyleSheet.create({
  strokeWidth: 8,
  strokeColor: '#2c3e50',
  drawingCanvas: {
    width: 300,
    height: 300,
    backgroundColor: 'white',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#dee2e6',
  },
});

// User Details Modal styles
export const UserDetailsModalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    backgroundColor: 'white',
    borderRadius: 12,
    width: '90%',
    maxWidth: 400,
    maxHeight: '80%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#e9ecef',
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2c3e50',
  },
  closeButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#f8f9fa',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButtonText: {
    fontSize: 16,
    color: '#6c757d',
    fontWeight: 'bold',
  },
  content: {
    padding: 20,
  },
  loadingContainer: {
    alignItems: 'center',
    padding: 40,
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: '#6c757d',
  },
  userInfoSection: {
    marginBottom: 20,
  },
  progressSection: {
    marginBottom: 30,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2c3e50',
    marginBottom: 15,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f8f9fa',
  },
  infoLabel: {
    fontSize: 16,
    color: '#6c757d',
    fontWeight: '500',
  },
  infoValue: {
    fontSize: 16,
    color: '#2c3e50',
    fontWeight: '600',
  },
  actionsSection: {
    alignItems: 'center',
  },
  resetButton: {
    backgroundColor: '#dc3545',
    paddingHorizontal: 30,
    paddingVertical: 12,
    borderRadius: 8,
    minWidth: 150,
    alignItems: 'center',
  },
  resetButtonDisabled: {
    backgroundColor: '#6c757d',
  },
  resetButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  errorContainer: {
    alignItems: 'center',
    padding: 40,
  },
  errorText: {
    fontSize: 16,
    color: '#dc3545',
    textAlign: 'center',
  },
});

// Quiz Mode Styles
export const QuizModeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#e9ecef',
  },
  backButton: {
    marginRight: 15,
  },
  backButtonText: {
    fontSize: 16,
    color: '#3498db',
    fontWeight: 'bold',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2c3e50',
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e9ecef',
  },
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginHorizontal: 5,
    borderRadius: 8,
    backgroundColor: '#f8f9fa',
    alignItems: 'center',
  },
  activeTabButton: {
    backgroundColor: '#3498db',
  },
  tabButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#6c757d',
  },
  activeTabButtonText: {
    color: '#ffffff',
  },
  content: {
    flex: 1,
    padding: 20,
  },
  quizStartContainer: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  quizTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2c3e50',
    marginBottom: 10,
    textAlign: 'center',
  },
  quizDescription: {
    fontSize: 16,
    color: '#6c757d',
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 24,
  },
  characterCount: {
    fontSize: 14,
    color: '#3498db',
    marginBottom: 30,
    fontWeight: 'bold',
  },
  quizLengthTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2c3e50',
    marginTop: 20,
    marginBottom: 15,
    textAlign: 'center',
  },
  quizLengthContainer: {
    width: '100%',
    marginBottom: 20,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  quizLengthButton: {
    backgroundColor: '#3498db',
    width: '48%',
    aspectRatio: 1,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  selectedQuizLengthButton: {
    backgroundColor: '#2980b9',
  },
  disabledQuizLengthButton: {
    backgroundColor: '#cccccc',
  },
  quizLengthButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#ffffff',
    textAlign: 'center',
  },
  selectedQuizLengthButtonText: {
    color: '#ffffff',
  },
  disabledQuizLengthButtonText: {
    color: '#666666',
  },
  questionContainer: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
  },
  progressContainer: {
    marginBottom: 20,
  },
  progressText: {
    fontSize: 14,
    color: '#6c757d',
    marginBottom: 8,
    textAlign: 'center',
  },
  progressBar: {
    height: 6,
    backgroundColor: '#e9ecef',
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#3498db',
  },
  questionContent: {
    alignItems: 'center',
  },
  characterContainer: {
    backgroundColor: '#f5f5f5',
    borderWidth: 2,
    borderColor: '#3498db',
    borderRadius: 15,
    padding: 20,
    marginBottom: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  characterDisplay: {
    fontSize: 48,
    fontWeight: 'bold',
    color: '#2c3e50',
  },
  pinyinDisplay: {
    fontSize: 18,
    color: '#3498db',
    marginBottom: 20,
    fontWeight: 'bold',
  },
  sentenceContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    backgroundColor: '#f5f5f5',
    padding: 15,
    borderRadius: 15,
    borderWidth: 2,
    borderColor: '#3498db',
  },
  sentenceDisplay: {
    fontSize: 36,
    color: '#2c3e50',
    textAlign: 'center',
    lineHeight: 44,
    fontWeight: 'bold',
  },
  blankSpace: {
    fontSize: 36,
    lineHeight: 44,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#3498db',
    textDecorationLine: 'underline',
    textDecorationColor: '#3498db',
    textDecorationStyle: 'solid',
    minWidth: 80,
  },
  sentencePinyin: {
    fontSize: 16,
    color: '#6c757d',
    marginBottom: 20,
    textAlign: 'center',
  },
  questionText: {
    fontSize: 16,
    color: '#6c757d',
    marginBottom: 20,
    textAlign: 'center',
  },
  optionsContainer: {
    position: 'relative',
    paddingHorizontal: 20,
    paddingVertical: 20,
    height: 360,
    width: '100%',
  },
  optionButton: {
    minWidth: 100,
    minHeight: 100,
    maxWidth: 140,
    maxHeight: 100,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  translationOptionButton: {
    width: '80%',
    minHeight: 60,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: '#f5f5f5',
    borderWidth: 2,
    borderColor: '#3498db',
    borderRadius: 30,
    marginVertical: 8,
  },
  selectedOption: {
    transform: [{ scale: 1.1 }],
    borderRadius: 60,
  },
  correctOption: {
    transform: [{ scale: 1.1 }],
    borderRadius: 60,
  },
  incorrectOption: {
    transform: [{ scale: 0.9 }],
    opacity: 0.6,
    borderRadius: 60,
  },
  balloonContainer: {
    width: 100,
    height: 100,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#bbdefb',
  },
  balloonEmoji: {
    fontSize: 50,
    textAlign: 'center',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 0,
    lineHeight: 100,
  },
  optionText: {
    fontSize: 24,
    color: '#2c3e50',
    textAlign: 'center',
    fontWeight: '900',
    zIndex: 1,
    flex: 1,
    textAlignVertical: 'center',
  },
  selectedOptionText: {
    color: '#3498db',
  },
  correctOptionText: {
    color: '#28a745',
  },
  incorrectOptionText: {
    color: '#dc3545',
  },
  // Translation Quiz Styles
  translationOptionsContainer: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 20,
    width: '100%',
  },
  selectedTranslationOption: {
    borderColor: '#3498db',
    backgroundColor: '#e3f2fd',
    borderRadius: 30,
  },
  correctTranslationOption: {
    borderColor: '#28a745',
    backgroundColor: '#d4edda',
    borderRadius: 30,
  },
  incorrectTranslationOption: {
    borderColor: '#dc3545',
    backgroundColor: '#f8d7da',
    borderRadius: 30,
  },
  translationOptionText: {
    fontSize: 18,
    color: '#000000',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  selectedTranslationOptionText: {
    color: '#3498db',
  },
  correctTranslationOptionText: {
    color: '#28a745',
  },
  incorrectTranslationOptionText: {
    color: '#dc3545',
  },
  resultContainer: {
    marginTop: 20,
    padding: 15,
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    width: '100%',
  },
  resultText: {
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 10,
  },
  correctResult: {
    color: '#28a745',
  },
  incorrectResult: {
    color: '#dc3545',
  },
  explanationText: {
    fontSize: 16,
    color: '#2c3e50',
    textAlign: 'center',
    marginTop: 0,
    marginBottom: 0,
    marginRight: 80,
    lineHeight: 22,
    fontWeight: 'bold',
  },
  nextQuestionButton: {
    position: 'absolute',
    right: 20,
    top: '33%',
    marginTop: -25,
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#3498db',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  nextQuestionArrow: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: 'bold',
  },
  completeContainer: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  completeTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#2c3e50',
    marginBottom: 15,
    textAlign: 'center',
  },
  scoreText: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#27ae60',
    textAlign: 'center',
    marginBottom: 10,
  },
  scoreDetails: {
    fontSize: 16,
    color: '#6c757d',
    textAlign: 'center',
    marginBottom: 20,
  },
  completeText: {
    fontSize: 18,
    color: '#6c757d',
    textAlign: 'center',
    marginBottom: 10,
  },
  completeSubtext: {
    fontSize: 16,
    color: '#3498db',
    textAlign: 'center',
    marginBottom: 30,
  },
  restartButton: {
    backgroundColor: '#3498db',
    paddingHorizontal: 30,
    paddingVertical: 15,
    borderRadius: 25,
  },
  restartButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
  },
});

// Material Icon Styles
export const MaterialIconStyles = StyleSheet.create({
  emojiIcon: {
    textAlign: 'center',
  },
});
